In [22]:
#Import the libraries
import numpy as np

In [23]:
B2 = np.array([[1,2],[1,1]])
B2

array([[1, 2],
       [1, 1]])

In [24]:
B1 = np.array([[1],[1]])
B1

array([[1],
       [1]])

In [25]:
# M is the inverse of B2
M = np.linalg.inv(B2)

In [26]:
M

array([[-1.,  2.],
       [ 1., -1.]])

In [27]:
B2 @ B1

array([[3],
       [2]])

----------------------

In [28]:
v1 = np.array([[3],[2]])
v1

array([[3],
       [2]])

In [29]:
B1 = np.array([[1,0],[0,1]])
B1

array([[1, 0],
       [0, 1]])

In [30]:
B2 = np.array([[3,-3],[4,-5]])
B2

array([[ 3, -3],
       [ 4, -5]])

In [31]:
# M is the inverse of B2
M = np.linalg.inv(B2)

In [32]:
M

array([[ 1.66666667, -1.        ],
       [ 1.33333333, -1.        ]])

In [33]:
v2 = M @ v1

In [34]:
v2

array([[3.],
       [2.]])

In [35]:
T1 = B1 @ v1

# 

In [36]:
T1

array([[3],
       [2]])

In [37]:
T2 = B2 @ v2
T2

array([[3.],
       [2.]])